package main

import (
	"log"
	"os"
	"path/filepath"
	"strings"

	"github.com/damedic/fhir-toolbox-go/internal/generate"
	"github.com/damedic/fhir-toolbox-go/internal/generate/fhirpath"
	"github.com/damedic/fhir-toolbox-go/internal/generate/ir"
	"github.com/damedic/fhir-toolbox-go/internal/generate/json"
	"github.com/damedic/fhir-toolbox-go/internal/generate/model"
	"github.com/damedic/fhir-toolbox-go/internal/generate/xml"
	"github.com/dave/jennifer/jen"
)

var (
	buildReleases         = []string{"R4", "R4B", "R5"}
	definitionsURLFmtStr  = "http://hl7.org/fhir/%s/definitions.json.zip"
	modelGenTarget        = "model/gen"
	capabilitiesGenTarget = "capabilities/gen"
	clientGenTarget       = "rest"
)

func main() {
	log.Println("Running code generation...")
	if err := os.RemoveAll(modelGenTarget); err != nil {
		panic(err)
	}
	if err := os.RemoveAll(capabilitiesGenTarget); err != nil {
		panic(err)
	}
	// Clean up generated client files
	cleanupGeneratedClientFiles(clientGenTarget)

	releaseTypes, releaseSearchParams, releaseValueSets := loadTypes(buildReleases)

	for _, r := range buildReleases {
		log.Printf("Generating for FHIR %v ...\n", r)

		log.Println("Generating structs and implementations...")

		generate.GenerateAll(releaseTypes[r], genDir(modelGenTarget, r), r,
			generate.ModelPkgDocGenerator{},
			generate.TypesGenerator{},
			generate.SearchParamsGenerator{SearchParams: releaseSearchParams},
			generate.ValueSetsGenerator{ValueSets: releaseValueSets[r]},
			generate.ImplResourceGenerator{},
			generate.ImplElementGenerator{},
			generate.StringerGenerator{},
			generate.OperationOutcomeErrorGenerator{},
			json.MarshalGenerator{},
			json.UnmarshalGenerator{},
			xml.MarshalGenerator{},
			xml.UnmarshalGenerator{},
			fhirpath.FHIRPathGenerator{},
		)

		generate.GenerateAll(releaseTypes[r], genDir(capabilitiesGenTarget, r), r,
			generate.CapabilityPkgDocGenerator{},
			generate.CapabilitiesGenerator{},
			generate.CapabilitiesWrapperGenerator{},
		)

		log.Println("Generating client...")
		generateClientFiles(releaseTypes[r], clientGenTarget, r)
	}

	// basic types generation removed

	log.Println("Code generation done.")
}

func cleanupGeneratedClientFiles(targetDir string) {
	// Remove generated client files for all releases
	for _, release := range buildReleases {
		filename := filepath.Join(targetDir, "gen_client_"+strings.ToLower(release)+".go")
		if err := os.Remove(filename); err != nil && !os.IsNotExist(err) {
			log.Printf("Warning: failed to remove %s: %v", filename, err)
		}
	}
}

func loadTypes(releases []string) (map[string][]ir.ResourceOrType, map[string]model.Bundle, map[string]model.Bundle) {
	types := map[string][]ir.ResourceOrType{}
	searchParams := map[string]model.Bundle{}
	valueSets := map[string]model.Bundle{}
	for _, r := range releases {
		zipPath := downloadDefinitions(r)
		bundles := readJSONFromZIP(zipPath)

		types[r] = append(ir.Parse(&bundles.types), ir.Parse(&bundles.resources)...)
		searchParams[r] = bundles.searchParams
		valueSets[r] = bundles.valueSets
	}
	return types, searchParams, valueSets
}

// basic types generation removed

func genDir(genTarget, release string) string {
	dir := filepath.Join(genTarget, strings.ToLower(release))

	err := os.MkdirAll(dir, os.ModePerm)
	if err != nil {
		log.Panic(err)
	}

	return dir
}

func generateClientFiles(types []ir.ResourceOrType, targetDir, release string) {
	resources := ir.FilterResources(types)

	// Create the file directly in the target directory
	filename := filepath.Join(targetDir, "gen_client_"+strings.ToLower(release)+".go")

	f := jen.NewFilePathName(targetDir, "rest")
	f.HeaderComment("// DO NOT EDIT!\n// Code generated by \"github.com/damedic/fhir-toolbox-go/internal/generate\";\n// use `make generate` to regenerate.")

	// Generate the client using the existing generator logic
	generate.GenerateUnifiedClient(f, resources, release)

	// Save the file
	err := f.Save(filename)
	if err != nil {
		log.Panic(err)
	}
}
